configure youtube quality in ytmp.conf and check if all vars are set in ytmp.conf

diff --git a/ytmpc b/ytmpc
--- a/ytmpc
+++ b/ytmpc
@@ -2,10 +2,18 @@
 
 CONFIG="${XDG_CONFIG_HOME:-"$HOME/.config"}/ytmp/"
 if [[ -f "$CONFIG/ytmp.conf" ]]; then
-    . "$CONFIG/ytmp.conf"
+    CONFPATH="$config/ytmp.conf"
 else
-    . /etc/ytmp.conf
+    CONFPATH="/etc/ytmp.conf"
 fi
+. $CONFPATH
+
+if [ ! $GUI ]; then echo "GUI not set in $CONFPATH"; error=true; fi
+if [ ! ${!DWN[@]} ]; then echo "DWN not set in $CONFPATH"; error=true; fi
+if [ ! $PLAYER ]; then echo "PLAYER not set in $CONFPATH"; error=true; fi
+if [ ! ${!YTQUAL[@]} ]; then echo "YTQUAL not set in $CONFPATH"; error=true; fi
+if [ $error ]; then exit 1; fi
+# http://stackoverflow.com/questions/874389/bash-test-for-a-variable-unset-using-a-function/1469472#1469472
 
 ytplay() {
   echo "[ytmpc] Now playing: ($host) $title"
@@ -15,7 +23,7 @@ ytplay() {
 ytdownload() {
   echo "[ytmpc] Now downloading: ($host) $title"
   case $host in
-    "youtube") youtube-dl --max-quality="$MAXQUAL" -o "${DWN:-$HOME}/%(stitle)s.%(ext)s" "http://www.youtube.com/watch?v=""$id";;
+    "youtube") youtube-dl $YTQUAL -o "${DWN:-$HOME}/%(stitle)s.%(ext)s" "http://www.youtube.com/watch?v=""$id";;
     "vimeo") wget -O "${DWN:-$HOME}/$title.flv" "$vidurl";;
   esac
 }
@@ -90,7 +98,7 @@ while(true); do
     if [[ "$id" != "$lastid" ]]; then
       case "$host" in
         "youtube") title="$(youtube-dl -e "http://www.youtube.com/watch?v=""$id")"
-                   vidurl="$(youtube-dl --max-quality="$MAXQUAL" -g "http://www.youtube.com/watch?v=""$id")";;
+                   vidurl="$(youtube-dl $YTQUAL -g "http://www.youtube.com/watch?v=""$id")";;
         "vimeo") parsevimeo;; 
       esac
       case "$GUI" in
